"""move transcripts to rounds

Revision ID: 0ccd2c25e4cb
Revises: a188cbf67b22
Create Date: 2026-01-23 21:06:55.996498

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ccd2c25e4cb"
down_revision: str | Sequence[str] | None = "a188cbf67b22"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applications", "transcript_summary")
    op.drop_column("applications", "transcript_path")
    op.add_column(
        "rounds", sa.Column("transcript_path", sa.String(length=500), nullable=True)
    )
    op.add_column("rounds", sa.Column("transcript_summary", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rounds", "transcript_summary")
    op.drop_column("rounds", "transcript_path")
    op.add_column(
        "applications",
        sa.Column("transcript_path", sa.VARCHAR(length=500), nullable=True),
    )
    op.add_column(
        "applications", sa.Column("transcript_summary", sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
