"""Address book, planning records, profile permissions and account requests."""

from datetime import UTC, datetime
from uuid import UUID, uuid4

import sqlalchemy as sa
from alembic import op

revision = "20261009_workspace"
down_revision = "20261008_language"
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    sqlite = bind.dialect.name == "sqlite"
    if sqlite:
        # SQLite requires FK enforcement off before recreating referenced tables.
        # Commit the preceding revision, then keep this revision atomic.
        bind.connection.dbapi_connection.commit()
        bind.exec_driver_sql("PRAGMA foreign_keys=OFF")
        bind.exec_driver_sql("BEGIN")
    try:
        _schema()
        _meanings()
        _data()
        if sqlite and bind.exec_driver_sql("PRAGMA foreign_key_check").fetchone():
            raise RuntimeError("Foreign key check failed during workspace migration")
        if sqlite:
            bind.connection.dbapi_connection.commit()
    except BaseException:
        if sqlite:
            bind.connection.dbapi_connection.rollback()
        raise
    finally:
        if sqlite:
            bind.exec_driver_sql("PRAGMA foreign_keys=ON")


def _schema():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("website", sa.String(length=2048), nullable=True),
        sa.Column("industry", sa.String(length=255), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("size", sa.String(length=20), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("culture_notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.current_timestamp(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_companies_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "contacts",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("function", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=100), nullable=True),
        sa.Column("profile_url", sa.String(length=2048), nullable=True),
        sa.Column("role", sa.String(length=100), nullable=True),
        sa.Column("last_contact_on", sa.Date(), nullable=True),
        sa.Column("communication_note", sa.Text(), nullable=True),
        sa.Column("company_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.current_timestamp(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_contacts_company_id"), ["company_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_contacts_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "application_contacts",
        sa.Column("application_id", sa.String(length=36), nullable=False),
        sa.Column("contact_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.current_timestamp(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "application_id", "contact_id", name="uq_application_contact"
        ),
    )
    with op.batch_alter_table("application_contacts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_application_contacts_application_id"),
            ["application_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_application_contacts_contact_id"),
            ["contact_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_application_contacts_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "application_documents",
        sa.Column("application_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("media_type", sa.String(length=100), nullable=False),
        sa.Column("byte_count", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.current_timestamp(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('portfolio','task','solution','other')", name="ck_document_kind"
        ),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("application_documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_application_documents_application_id"),
            ["application_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_application_documents_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "notes",
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.current_timestamp(),
            nullable=False,
        ),
        sa.Column("lead_id", sa.String(length=36), nullable=True),
        sa.Column("application_id", sa.String(length=36), nullable=True),
        sa.Column("company_id", sa.String(length=36), nullable=True),
        sa.Column("contact_id", sa.String(length=36), nullable=True),
        sa.Column("round_id", sa.String(length=36), nullable=True),
        sa.CheckConstraint(
            "(CASE WHEN lead_id IS NULL THEN 0 ELSE 1 END) + (CASE WHEN application_id IS NULL THEN 0 ELSE 1 END) + (CASE WHEN company_id IS NULL THEN 0 ELSE 1 END) + (CASE WHEN contact_id IS NULL THEN 0 ELSE 1 END) + (CASE WHEN round_id IS NULL THEN 0 ELSE 1 END) = 1",
            name="ck_note_one_target",
        ),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["lead_id"], ["job_leads.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["round_id"], ["rounds.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notes_application_id"), ["application_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notes_company_id"), ["company_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notes_contact_id"), ["contact_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_notes_lead_id"), ["lead_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_notes_round_id"), ["round_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_notes_user_id"), ["user_id"], unique=False)

    op.create_table(
        "reminders",
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_zone", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=20), server_default="open", nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("intent_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.current_timestamp(),
            nullable=False,
        ),
        sa.Column("lead_id", sa.String(length=36), nullable=True),
        sa.Column("application_id", sa.String(length=36), nullable=True),
        sa.Column("company_id", sa.String(length=36), nullable=True),
        sa.Column("contact_id", sa.String(length=36), nullable=True),
        sa.Column("round_id", sa.String(length=36), nullable=True),
        sa.CheckConstraint(
            "kind IN ('application_deadline','reply_to_company','interview','interview_preparation','task_submission','recruiter_follow_up','expected_feedback')",
            name="ck_reminder_kind",
        ),
        sa.CheckConstraint(
            "state IN ('open','done','dismissed')", name="ck_reminder_state"
        ),
        sa.CheckConstraint(
            "(CASE WHEN lead_id IS NULL THEN 0 ELSE 1 END) + (CASE WHEN application_id IS NULL THEN 0 ELSE 1 END) + (CASE WHEN company_id IS NULL THEN 0 ELSE 1 END) + (CASE WHEN contact_id IS NULL THEN 0 ELSE 1 END) + (CASE WHEN round_id IS NULL THEN 0 ELSE 1 END) <= 1",
            name="ck_reminder_one_target",
        ),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["lead_id"], ["job_leads.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["round_id"], ["rounds.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "intent_id", name="uq_reminder_owner_intent"),
    )
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_reminders_application_id"), ["application_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_reminders_company_id"), ["company_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_reminders_contact_id"), ["contact_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_reminders_due_at"), ["due_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_reminders_lead_id"), ["lead_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_reminders_round_id"), ["round_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_reminders_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "round_contacts",
        sa.Column("round_id", sa.String(length=36), nullable=False),
        sa.Column("contact_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.current_timestamp(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["round_id"], ["rounds.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("round_id", "contact_id", name="uq_round_contact"),
    )
    with op.batch_alter_table("round_contacts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_round_contacts_contact_id"), ["contact_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_round_contacts_round_id"), ["round_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_round_contacts_user_id"), ["user_id"], unique=False
        )

    with op.batch_alter_table("application_status_history", schema=None) as batch_op:
        batch_op.add_column(sa.Column("reason", sa.Text(), nullable=True))

    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(sa.Column("outcome_reason", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("source_text", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "source_revision", sa.Integer(), server_default="0", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column("company_id", sa.String(length=36), nullable=True)
        )
        batch_op.add_column(
            sa.Column("recruiter_contact_id", sa.String(length=36), nullable=True)
        )
        batch_op.add_column(sa.Column("work_mode", sa.String(length=30), nullable=True))
        batch_op.add_column(
            sa.Column("employment_type", sa.String(length=30), nullable=True)
        )
        batch_op.add_column(sa.Column("seniority", sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column("deadline", sa.Date(), nullable=True))
        batch_op.add_column(
            sa.Column("pay_period", sa.String(length=20), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "priority",
                sa.String(length=10),
                server_default="normal",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("tags", sa.JSON(), server_default="[]", nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "confirmed_requirements", sa.JSON(), server_default="[]", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "requirements_revision",
                sa.Integer(),
                server_default="0",
                nullable=False,
            )
        )
        batch_op.alter_column("applied_at", existing_type=sa.DATE(), nullable=True)
        batch_op.create_index(
            batch_op.f("ix_applications_company_id"), ["company_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_applications_recruiter_contact_id",
            "contacts",
            ["recruiter_contact_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            "fk_applications_company_id",
            "companies",
            ["company_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("job_leads", schema=None) as batch_op:
        batch_op.add_column(sa.Column("decision", sa.String(length=20), nullable=True))
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.func.current_timestamp(),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("company_id", sa.String(length=36), nullable=True)
        )
        batch_op.add_column(
            sa.Column("recruiter_contact_id", sa.String(length=36), nullable=True)
        )
        batch_op.add_column(sa.Column("work_mode", sa.String(length=30), nullable=True))
        batch_op.add_column(
            sa.Column("employment_type", sa.String(length=30), nullable=True)
        )
        batch_op.add_column(sa.Column("seniority", sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column("deadline", sa.Date(), nullable=True))
        batch_op.add_column(
            sa.Column("pay_period", sa.String(length=20), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "priority",
                sa.String(length=10),
                server_default="normal",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("tags", sa.JSON(), server_default="[]", nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "confirmed_requirements", sa.JSON(), server_default="[]", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "requirements_revision",
                sa.Integer(),
                server_default="0",
                nullable=False,
            )
        )
        batch_op.alter_column(
            "url", existing_type=sa.VARCHAR(length=2048), nullable=True
        )
        batch_op.create_index(
            batch_op.f("ix_job_leads_company_id"), ["company_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_job_leads_company_id",
            "companies",
            ["company_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            "fk_job_leads_recruiter_contact_id",
            "contacts",
            ["recruiter_contact_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("rounds", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("revision", sa.Integer(), server_default="0", nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.func.current_timestamp(),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("time_zone", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(sa.Column("duration_minutes", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("mode", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("location", sa.String(length=500), nullable=True))
        batch_op.add_column(
            sa.Column("meeting_url", sa.String(length=2048), nullable=True)
        )
        batch_op.add_column(
            sa.Column("preparation", sa.JSON(), server_default="{}", nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "questions_answers", sa.JSON(), server_default="[]", nullable=False
            )
        )
        batch_op.add_column(sa.Column("impressions", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("task_description", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("task_deadline", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(sa.Column("next_steps", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("expected_reply_on", sa.Date(), nullable=True))

    with op.batch_alter_table("user_profiles", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("revision", sa.Integer(), server_default="0", nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "permission_revision", sa.Integer(), server_default="0", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column("ai_permissions", sa.JSON(), server_default="{}", nullable=False)
        )
        batch_op.add_column(
            sa.Column("display_name", sa.String(length=255), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "desired_positions", sa.JSON(), server_default="[]", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column("fields_of_work", sa.JSON(), server_default="[]", nullable=False)
        )
        batch_op.add_column(sa.Column("seniority", sa.String(length=50), nullable=True))
        batch_op.add_column(
            sa.Column("work_modes", sa.JSON(), server_default="[]", nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "employment_types", sa.JSON(), server_default="[]", nullable=False
            )
        )
        batch_op.add_column(sa.Column("years_experience", sa.Float(), nullable=True))
        batch_op.add_column(
            sa.Column("location_restrictions", sa.Text(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("skill_items", sa.JSON(), server_default="[]", nullable=False)
        )
        batch_op.add_column(
            sa.Column("technologies", sa.JSON(), server_default="[]", nullable=False)
        )
        batch_op.add_column(
            sa.Column("projects", sa.JSON(), server_default="[]", nullable=False)
        )
        batch_op.add_column(
            sa.Column("certificates", sa.JSON(), server_default="[]", nullable=False)
        )
        batch_op.add_column(
            sa.Column("languages", sa.JSON(), server_default="[]", nullable=False)
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "approval_pending",
                sa.Boolean(),
                server_default=sa.false(),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True)
        )


def _meanings():
    meanings = "'unknown','preparing','applied','screening','interviewing','offer','accepted','rejected','withdrawn','no_reply'"
    for table, fields in [
        ("application_statuses", [("ck_status_meaning", "meaning")]),
        ("applications", [("ck_application_status_meaning", "status_meaning")]),
        (
            "application_status_history",
            [
                ("ck_history_from_meaning", "from_meaning"),
                ("ck_history_to_meaning", "to_meaning"),
            ],
        ),
    ]:
        with op.batch_alter_table(table) as batch:
            if table == "application_status_history":
                batch.drop_constraint("ck_history_gap", type_="check")
                batch.create_check_constraint(
                    "ck_history_gap",
                    "(is_gap AND from_status_id IS NULL AND to_status_id IS NULL AND from_meaning IS NULL AND to_meaning IS NULL AND note IS NULL AND reason IS NULL AND corrected_at IS NULL AND correction_note IS NULL) OR (NOT is_gap AND to_status_id IS NOT NULL)",
                )
            for name, field in fields:
                batch.drop_constraint(name, type_="check")
                batch.create_check_constraint(
                    name, f"{field} IS NULL OR {field} IN ({meanings})"
                )


def _data():
    bind = op.get_bind()
    metadata = sa.MetaData()
    tables = {
        name: sa.Table(name, metadata, autoload_with=bind)
        for name in (
            "companies",
            "contacts",
            "application_contacts",
            "job_leads",
            "applications",
            "user_profiles",
            "application_statuses",
        )
    }
    now = datetime.now(UTC)
    companies = {}
    recruiters = {}
    for name in ("job_leads", "applications"):
        table = tables[name]
        for row in bind.execute(sa.select(table)).mappings().all():
            recorded_at = (
                row["scraped_at"] if name == "job_leads" else row["created_at"]
            )
            activity_at = recorded_at if name == "job_leads" else row["updated_at"]
            values = {"updated_at": activity_at} if name == "job_leads" else {}
            company = (row["company"] or "").strip()
            if company:
                key = (row["user_id"], company)
                if key not in companies:
                    companies[key] = str(uuid4())
                    bind.execute(
                        tables["companies"]
                        .insert()
                        .values(
                            id=companies[key],
                            user_id=row["user_id"],
                            name=company,
                            created_at=now,
                            updated_at=now,
                        )
                    )
                values["company_id"] = companies[key]
            if any(
                row[k]
                for k in ("recruiter_name", "recruiter_title", "recruiter_linkedin_url")
            ):
                pair = row["id"] if name == "job_leads" else row["job_lead_id"]
                key = (
                    row["user_id"],
                    pair or row["id"],
                    values.get("company_id"),
                    row["recruiter_name"],
                    row["recruiter_title"],
                    row["recruiter_linkedin_url"],
                )
                if key not in recruiters:
                    recruiters[key] = str(uuid4())
                    bind.execute(
                        tables["contacts"]
                        .insert()
                        .values(
                            id=recruiters[key],
                            user_id=row["user_id"],
                            name=row["recruiter_name"]
                            or row["recruiter_title"]
                            or "Recruiter",
                            function=row["recruiter_title"],
                            profile_url=row["recruiter_linkedin_url"],
                            role="Recruiter",
                            company_id=values.get("company_id"),
                            created_at=recorded_at,
                            updated_at=activity_at,
                        )
                    )
                values["recruiter_contact_id"] = recruiters[key]
                if name == "applications":
                    bind.execute(
                        tables["application_contacts"]
                        .insert()
                        .values(
                            id=str(uuid4()),
                            user_id=row["user_id"],
                            application_id=row["id"],
                            contact_id=recruiters[key],
                            created_at=now,
                            updated_at=now,
                        )
                    )
            if values:
                bind.execute(
                    table.update().where(table.c.id == row["id"]).values(**values)
                )
    profile = tables["user_profiles"]
    for row in bind.execute(sa.select(profile)).mappings().all():
        values = {}
        used_ids = set()
        for field in ("work_history", "education", "skills"):
            entries = row[field]
            if entries is None:
                entries = []
            if not isinstance(entries, list):
                entries = [entries]
            items = []
            for entry in entries:
                if isinstance(entry, dict):
                    item = dict(entry)
                elif field == "skills" and isinstance(entry, str):
                    item = {"name": entry}
                else:
                    item = {"legacy_value": entry, "needs_repair": True}
                previous_id = item.get("id")
                try:
                    item_id = str(UUID(str(previous_id)))
                    if item_id in used_ids:
                        raise ValueError("Duplicate legacy identity")
                except ValueError:
                    if previous_id is not None:
                        item["legacy_id"] = previous_id
                    item_id = str(uuid4())
                item["id"] = item_id
                used_ids.add(item_id)
                for key in (
                    "title",
                    "company",
                    "description",
                    "institution",
                    "degree",
                    "field",
                    "name",
                ):
                    if (
                        key in item
                        and item[key] is not None
                        and not isinstance(item[key], str)
                    ):
                        item["needs_repair"] = True
                items.append(item)
            values["skill_items" if field == "skills" else field] = items
        bind.execute(profile.update().where(profile.c.id == row["id"]).values(**values))
    # Preparing is installed by the existing idempotent startup seed, just like
    # every other built-in status. Migration does not invent reference rows.


def downgrade():
    raise RuntimeError(
        "Workspace downgrade would discard personal data; restore a pre-upgrade backup instead"
    )
