"""Add job leads and user profiles

Revision ID: 2359baec93ce
Revises: 913e52a54449
Create Date: 2026-02-14 11:07:33.702118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2359baec93ce'
down_revision: Union[str, Sequence[str], None] = '913e52a54449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('recruiter_name', sa.String(length=255), nullable=True),
    sa.Column('recruiter_title', sa.String(length=255), nullable=True),
    sa.Column('recruiter_linkedin_url', sa.String(length=512), nullable=True),
    sa.Column('requirements_must_have', sa.JSON(), nullable=False),
    sa.Column('requirements_nice_to_have', sa.JSON(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('years_experience_min', sa.Integer(), nullable=True),
    sa.Column('years_experience_max', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('converted_to_application_id', sa.String(length=36), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['converted_to_application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_leads_user_id'), 'job_leads', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=512), nullable=True),
    sa.Column('authorized_to_work', sa.String(length=100), nullable=True),
    sa.Column('requires_sponsorship', sa.Boolean(), nullable=True),
    sa.Column('work_history', sa.JSON(), nullable=True),
    sa.Column('education', sa.JSON(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_application_status_history_application_id'), 'application_status_history', ['application_id'], unique=False)
    op.add_column('applications', sa.Column('job_lead_id', sa.String(length=36), nullable=True))
    op.add_column('applications', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('salary_min', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('salary_max', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('salary_currency', sa.String(length=10), nullable=True))
    op.add_column('applications', sa.Column('recruiter_name', sa.String(length=255), nullable=True))
    op.add_column('applications', sa.Column('recruiter_linkedin_url', sa.String(length=512), nullable=True))
    op.add_column('applications', sa.Column('requirements_must_have', sa.JSON(), nullable=False))
    op.add_column('applications', sa.Column('requirements_nice_to_have', sa.JSON(), nullable=False))
    op.add_column('applications', sa.Column('source', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_applications_job_lead_id'), 'applications', ['job_lead_id'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_applications_job_lead_id', 'job_leads', ['job_lead_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_rounds_application_id'), 'rounds', ['application_id'], unique=False)
    op.add_column('users', sa.Column('api_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'api_token')
    op.drop_index(op.f('ix_rounds_application_id'), table_name='rounds')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_lead_id'), table_name='applications')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_applications_job_lead_id', type_='foreignkey')
        batch_op.drop_column('source')
        batch_op.drop_column('requirements_nice_to_have')
        batch_op.drop_column('requirements_must_have')
        batch_op.drop_column('recruiter_linkedin_url')
        batch_op.drop_column('recruiter_name')
        batch_op.drop_column('salary_currency')
        batch_op.drop_column('salary_max')
        batch_op.drop_column('salary_min')
        batch_op.drop_column('description')
        batch_op.drop_column('job_lead_id')
    op.drop_index(op.f('ix_application_status_history_application_id'), table_name='application_status_history')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_job_leads_user_id'), table_name='job_leads')
    op.drop_table('job_leads')
    # ### end Alembic commands ###
