"""add schema hygiene indexes

Revision ID: 30e6bafac1f1
Revises: 20260409_schema_parity
Create Date: 2026-04-09 23:09:28.816276

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "30e6bafac1f1"
down_revision: str | None = "20260409_schema_parity"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_application_status_history_application_id"),
        table_name="application_status_history",
    )
    op.create_index(
        "ix_application_status_history_application_changed_at",
        "application_status_history",
        ["application_id", "changed_at"],
        unique=False,
    )
    op.drop_index(op.f("ix_applications_user_id"), table_name="applications")
    op.create_index("ix_applications_status_id", "applications", ["status_id"], unique=False)
    op.create_index(
        "ix_applications_user_applied_created",
        "applications",
        ["user_id", "applied_at", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_applications_user_job_url",
        "applications",
        ["user_id", "job_url"],
        unique=False,
        sqlite_where=sa.text("job_url IS NOT NULL"),
        postgresql_where=sa.text("job_url IS NOT NULL"),
    )
    op.create_index(
        "ix_applications_user_source_applied_created",
        "applications",
        ["user_id", "source", "applied_at", "created_at"],
        unique=False,
        sqlite_where=sa.text("source IS NOT NULL"),
        postgresql_where=sa.text("source IS NOT NULL"),
    )
    op.create_index(
        "ix_applications_user_status_applied_created",
        "applications",
        ["user_id", "status_id", "applied_at", "created_at"],
        unique=False,
    )
    op.drop_index(op.f("ix_job_leads_user_id"), table_name="job_leads")
    op.create_index(
        "ix_job_leads_user_scraped_at",
        "job_leads",
        ["user_id", "scraped_at"],
        unique=False,
    )
    op.create_index(
        "ix_job_leads_user_source_scraped_at",
        "job_leads",
        ["user_id", "source", "scraped_at"],
        unique=False,
        sqlite_where=sa.text("source IS NOT NULL"),
        postgresql_where=sa.text("source IS NOT NULL"),
    )
    op.create_index("ix_job_leads_user_url", "job_leads", ["user_id", "url"], unique=False)
    op.create_index("ix_round_media_round_id", "round_media", ["round_id"], unique=False)
    op.create_index("ix_rounds_round_type_id", "rounds", ["round_type_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_rounds_round_type_id", table_name="rounds")
    op.drop_index("ix_round_media_round_id", table_name="round_media")
    op.drop_index("ix_job_leads_user_url", table_name="job_leads")
    op.drop_index("ix_job_leads_user_source_scraped_at", table_name="job_leads")
    op.drop_index("ix_job_leads_user_scraped_at", table_name="job_leads")
    op.create_index(op.f("ix_job_leads_user_id"), "job_leads", ["user_id"], unique=False)
    op.drop_index("ix_applications_user_status_applied_created", table_name="applications")
    op.drop_index("ix_applications_user_source_applied_created", table_name="applications")
    op.drop_index("ix_applications_user_job_url", table_name="applications")
    op.drop_index("ix_applications_user_applied_created", table_name="applications")
    op.drop_index("ix_applications_status_id", table_name="applications")
    op.create_index(op.f("ix_applications_user_id"), "applications", ["user_id"], unique=False)
    op.drop_index(
        "ix_application_status_history_application_changed_at",
        table_name="application_status_history",
    )
    op.create_index(
        op.f("ix_application_status_history_application_id"),
        "application_status_history",
        ["application_id"],
        unique=False,
    )
    # ### end Alembic commands ###
