"""add audit log table

Revision ID: 50dd97924e9f
Revises: 38dc3fecbac5
Create Date: 2026-01-30 17:09:10.891156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50dd97924e9f'
down_revision: Union[str, Sequence[str], None] = '38dc3fecbac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_index(op.f('ix_status_history_app'), table_name='application_status_history')
    op.drop_index(op.f('ix_status_history_changed_at'), table_name='application_status_history')
    op.drop_index(op.f('ix_application_statuses_order'), table_name='application_statuses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_application_statuses_order'), 'application_statuses', ['order'], unique=False)
    op.create_index(op.f('ix_status_history_changed_at'), 'application_status_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_status_history_app'), 'application_status_history', ['application_id'], unique=False)
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
