"""add document fields

Revision ID: a188cbf67b22
Revises: c1f1dc6361b7
Create Date: 2026-01-21 13:07:53.579129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a188cbf67b22'
down_revision: Union[str, Sequence[str], None] = 'c1f1dc6361b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('cover_letter_path', sa.String(length=500), nullable=True))
    op.add_column('applications', sa.Column('transcript_path', sa.String(length=500), nullable=True))
    op.add_column('applications', sa.Column('transcript_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'transcript_summary')
    op.drop_column('applications', 'transcript_path')
    op.drop_column('applications', 'cover_letter_path')
    # ### end Alembic commands ###
