"""Add missing extraction fields to applications

Revision ID: fb5feec1a36e
Revises: c25e8753ada4
Create Date: 2026-02-16 20:50:10.094571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5feec1a36e'
down_revision: Union[str, Sequence[str], None] = 'c25e8753ada4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: location and recruiter_title already exist in the database
    op.add_column('applications', sa.Column('skills', sa.JSON(), nullable=True))
    op.add_column('applications', sa.Column('years_experience_min', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('years_experience_max', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'years_experience_max')
    op.drop_column('applications', 'years_experience_min')
    op.drop_column('applications', 'skills')
    # ### end Alembic commands ###
